/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rxjava;

import io.reactivex.Observable;

public class Library {
    public boolean someLibraryMethod() {
    	Integer[] arr = {100, 200, 300};
		Observable<Integer> source = Observable.fromArray(arr);
		source.subscribe(System.out::println);
        return true;
    }
}
